# Umbraco Magical Build Pipeline
# Worry less about build stuff and code more...
#
# 1. Ensure Secret Store has 'UMB_API_KEY' for pushing the ZIP package to our.umbraco.com
name: Magical Build
on:
  push:
    branches:
      - develop                          # Push events on master branch.
jobs:
  unicorn-dust:                         # Name of Job
    runs-on: windows-latest             # Make sure we run this on a Windows VM/image
    env:
      PKG_VERSION: '2.0.0-beta'              # UPDATE ME
    steps:
      - uses: actions/checkout@master   # Go & fetch the REPO & do a git checkout
      - uses: actions/setup-dotnet@v1   # Downloads & adds dotnet to PATH
        with:
          dotnet-version: '2.2.103'     # SDK Version to use
      - name: Setup Nuget.exe in PATH
        uses: warrenbuckley/Setup-Nuget@v1
      - name : Nuget restore
        working-directory: './src'    
        run : nuget restore
      - name: dotnet msbuild               # Build the project
        working-directory: './src'
        run: dotnet msbuild  /p:Configuration=Release /restore
      - name: dotnet vstests               # Runs tests
        working-directory: './src'
        run: dotnet vstest Our.Umbraco.Nexu.Web.Tests\bin\Release\Our.Umbraco.Nexu.Web.Tests.dll Our.Umbraco.Nexu.Core.Tests\bin\Release\Our.Umbraco.Nexu.Core.Tests.dll Our.Umbraco.Nexu.Parsers.Tests\bin\Release\Our.Umbraco.Nexu.Parsers.Tests.dll
      - name: Copy DLL/s into build.tmp.package folder  # All files/folders in build.tmp.package will be added to Umbraco ZIP package
        run: xcopy src\Our.Umbraco.Nexu.Web\bin\Release\Our.Umbraco.Nexu.*.dll build.tmp.package\bin\
      - name: Copy App_Plugins into build.tmp.package folder  # All files/folders in build.tmp.package will be added to Umbraco ZIP package
        run: xcopy /s /e src\Our.Umbraco.Nexu.Web\App_Plugins\ build.tmp.package\App_Plugins\
      - name: Create Umbraco ZIP package
        uses: warrenbuckley/Create-Umbraco-ZIP-Package@releases/v1
        with:
          packageXmlPath: 'Packaging/github-package.xml'     # The path to the Umbraco Package.xml that we use to build the package
          packageFilesPath: 'build.tmp.package'   # The path to the folder containing all the files needed for the package, excluding the package.xml (XCOPY is copying them here for us)
          packageVersion: ${{ env.PKG_VERSION }}  # A version for the Umbraco package such as 1.3.2
          packageZipOutPath: output               # Name of folder to put the Umbraco package ZIP in
      - name: Upload output folder as an artifact ZIP (Nupkg & Umb.zip)
        uses: actions/upload-artifact@master
        with:
          name: package-artifacts   # Name of the ZIP
          path: output              # Name of folder to ZIP up & upload as artifacts

